name: Deploy Project

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Authenticate with Google Cloud
      uses: google-github-actions/auth@v2
      with:
        credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v2

    - name: Deploy q1_memory
      run: |
        gcloud functions deploy q1_memory \
          --entry-point=q1_memory \
          --runtime python39 \
          --trigger-http \
          --allow-unauthenticated \
          --region us-central1 \
          --memory=1GB \
          --source ./src/cloud_functions/q1_memory

    - name: Deploy q2_memory
      run: |
        gcloud functions deploy q2_memory \
          --entry-point=q2_memory \
          --runtime python39 \
          --trigger-http \
          --allow-unauthenticated \
          --region us-central1 \
          --memory=1GB \
          --source ./src/cloud_functions/q2_memory \
          --set-env-vars GCP_PROJECT_ID=${{ secrets.GCP_PROJECT_ID }}

    - name: Deploy process_emoji_message
      run: |
        gcloud functions deploy process_emoji_message \
          --entry-point=process_emoji_message \
          --runtime python39 \
          --trigger-topic emoji-topic \
          --region us-central1 \
          --memory=1GB \
          --source ./src/cloud_functions/process_emoji_message
          
          